DROP TABLE IF EXISTS `t_user_0`;
CREATE TABLE `t_user_0` (
  `id` BIGINT ( 11 ) NOT NULL,
  `user_name` VARCHAR ( 255 ) DEFAULT NULL,
  `nick_name` VARCHAR ( 255 ) DEFAULT NULL,
  `address` VARCHAR ( 255 ) DEFAULT NULL,
  `age` INT ( 11 ) DEFAULT NULL,
  `remark` VARCHAR ( 255 ) DEFAULT NULL,
  PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS `t_user_1`;
CREATE TABLE `t_user_1` (
  `id` BIGINT ( 11 ) NOT NULL,
  `user_name` VARCHAR ( 255 ) DEFAULT NULL,
  `nick_name` VARCHAR ( 255 ) DEFAULT NULL,
  `address` VARCHAR ( 255 ) DEFAULT NULL,
  `age` INT ( 11 ) DEFAULT NULL,
  `remark` VARCHAR ( 255 ) DEFAULT NULL,
  PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS `t_user_2`;
CREATE TABLE `t_user_2` (
  `id` BIGINT ( 11 ) NOT NULL,
  `user_name` VARCHAR ( 255 ) DEFAULT NULL,
  `nick_name` VARCHAR ( 255 ) DEFAULT NULL,
  `address` VARCHAR ( 255 ) DEFAULT NULL,
  `age` INT ( 11 ) DEFAULT NULL,
  `remark` VARCHAR ( 255 ) DEFAULT NULL,
  PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS `t_user_3`;
CREATE TABLE `t_user_3` (
  `id` BIGINT ( 11 ) NOT NULL,
  `user_name` VARCHAR ( 255 ) DEFAULT NULL,
  `nick_name` VARCHAR ( 255 ) DEFAULT NULL,
  `address` VARCHAR ( 255 ) DEFAULT NULL,
  `age` INT ( 11 ) DEFAULT NULL,
  `remark` VARCHAR ( 255 ) DEFAULT NULL,
  PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS `t_user_4`;
CREATE TABLE `t_user_4` (
  `id` BIGINT ( 11 ) NOT NULL,
  `user_name` VARCHAR ( 255 ) DEFAULT NULL,
  `nick_name` VARCHAR ( 255 ) DEFAULT NULL,
  `address` VARCHAR ( 255 ) DEFAULT NULL,
  `age` INT ( 11 ) DEFAULT NULL,
  `remark` VARCHAR ( 255 ) DEFAULT NULL,
  PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;